import {
  ArrowClockwise,
  ArrowLeft,
  ArrowsCounterClockwise,
  Article,
  Bell,
  BookOpen,
  Brain,
  Calendar,
  CalendarBlank,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartBar,
  ChartLine,
  Check,
  CheckCircle,
  Clock,
  CloudArrowDown,
  CloudArrowUp,
  DotsSixVertical,
  Download,
  Eye,
  EyeSlash,
  FileText,
  FloppyDisk,
  Funnel,
  Gavel,
  Gear,
  Info,
  Lightning,
  MagnifyingGlass,
  PaperPlaneTilt,
  Pause,
  PencilSimple,
  Play,
  Plug,
  PlugsConnected,
  Plus,
  Pulse,
  Robot,
  ShieldCheck,
  ShieldSlash,
  ShieldWarning,
  Siren,
  Sparkle,
  SpinnerGap,
  Tag,
  Tray,
  TrendDown,
  TrendUp,
  User,
  UserMinus,
  UserPlus,
  Users,
  Warning,
  WarningCircle,
  X,
  XCircle
} from '@phosphor-icons/react'
import type { Icon } from '@phosphor-icons/react'

/**
 * Lucide-to-Phosphor icon lookup table for Phase 4 migration.
 *
 * Keys are the Lucide icon names currently imported across
 * `src/renderer/`. Values are Phosphor equivalents that most closely
 * match the Apple/Phosphor aesthetic. Panels should migrate by replacing
 * `import { Lucide } from 'lucide-react'` with
 * `import { IconMap } from '@renderer/components/ui-native/icons/icon-map'`
 * and reading `IconMap.Lucide` — or, once migrated, import the Phosphor
 * name directly and delete the Lucide import.
 */
export const IconMap = {
  Activity: Pulse,
  AlertCircle: WarningCircle,
  AlertTriangle: Warning,
  ArrowLeft,
  BarChart3: ChartBar,
  BookOpen,
  Bot: Robot,
  Brain,
  Calendar,
  CalendarDays: Calendar,
  Check,
  CheckCircle,
  CheckCircle2: CheckCircle,
  CheckIcon: Check,
  ChevronDownIcon: CaretDown,
  ChevronLeft: CaretLeft,
  ChevronRight: CaretRight,
  ChevronUpIcon: CaretUp,
  Clock,
  Download,
  Eye,
  EyeOff: EyeSlash,
  FileBarChart: ChartLine,
  FileText,
  Filter: Funnel,
  Flag: Tag,
  Gavel,
  GripVertical: DotsSixVertical,
  History: ArrowsCounterClockwise,
  Inbox: Tray,
  Info,
  LayoutDashboard: ChartBar,
  Loader2: SpinnerGap,
  MessageSquare: Bell,
  Pause,
  Pencil: PencilSimple,
  Play,
  Plug,
  Plus,
  RefreshCw: ArrowClockwise,
  RotateCcw: ArrowsCounterClockwise,
  Save: FloppyDisk,
  ScrollText: Article,
  Search: MagnifyingGlass,
  Send: PaperPlaneTilt,
  Settings: Gear,
  Settings2: Gear,
  Shield: ShieldCheck,
  ShieldAlert: ShieldWarning,
  ShieldCheck,
  ShieldOff: ShieldSlash,
  Siren,
  Sparkles: Sparkle,
  Tag,
  ToggleLeft: Plug,
  ToggleRight: PlugsConnected,
  Trash2: X,
  TrendingDown: TrendDown,
  TrendingUp: TrendUp,
  Unplug: Plug,
  Upload: CloudArrowUp,
  Download2: CloudArrowDown,
  User,
  UserPlus,
  UserX: UserMinus,
  Users,
  X,
  XCircle,
  Zap: Lightning,
  CalendarBlank,
  Bell
} satisfies Record<string, Icon>

export type IconName = keyof typeof IconMap
export type PhosphorIcon = Icon
